# Generated by Django 6.0.4 on 2026-05-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_project_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timeline',
            field=models.CharField(choices=[('undefined', 'To be defined'), ('short', 'Short-term'), ('medium', 'Medium-term'), ('long', 'Long-term')], default='undefined', max_length=20),
        ),
    ]
